# Generated by Django 4.2.2 on 2023-07-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("relaciones", "0002_tipocombustible_fabricante_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipocombustible",
            name="nombre",
            field=models.CharField(
                choices=[
                    ("Gasolina", "Gasolina"),
                    ("Gas", "Gas"),
                    ("Diesel", "Diesel"),
                    ("Biodiesel", "Biodiesel"),
                ],
                max_length=255,
                verbose_name="Tipo Combustible",
            ),
        ),
        migrations.CreateModel(
            name="DirectorEjecutivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Director Ejecutivo"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actuialización"
                    ),
                ),
                (
                    "fabrica",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relaciones.fabricante",
                    ),
                ),
            ],
        ),
    ]
