# Generated by Django 4.2.2 on 2023-07-04 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relaciones", "0003_alter_tipocombustible_nombre_directorejecutivo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directorejecutivo",
            old_name="fabrica",
            new_name="fabricante",
        ),
    ]
