# Generated by Django 4.2.2 on 2023-07-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0002_alter_empleado_emp_correo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="emp_designacion",
            field=models.CharField(
                choices=[
                    ("Project Manager", "Project Manager"),
                    ("Programador", "Programador"),
                    ("Soporte Técnico", "Soporte Técnico"),
                    ("Desarrollador Web", "Desarrollador Web"),
                ],
                max_length=150,
                verbose_name="Designación",
            ),
        ),
    ]
