# Generated by Django 4.2.2 on 2023-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migraciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preciohistoricovehiculo",
            name="color",
            field=models.CharField(default="Desconocido", max_length=50),
        ),
        migrations.AlterField(
            model_name="preciohistoricovehiculo",
            name="modelo",
            field=models.TextField(verbose_name="Modelo"),
        ),
    ]
